---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: blog
  label: Blog
  create: documents
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: vuepress build -d .vuepress/dist
  preview_output_directory: dist
  output_directory: ".vuepress/dist"
  instant_preview_command: gridsome build
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
